import { useMemo, useState } from 'react'
import { formatShortDate, safeTime } from '../lib/date.js'
const STATUSES=[['pendiente','Pendiente'],['en_progreso','En progreso'],['pospuesta','Pospuesta'],['bloqueada','Bloqueada'],['cancelada','Cancelada'],['completada','Completada']]
export default function AdvancedTasksView({tasks,taskSubtasks,tags,taskTagLinks,onNew,onEdit,onToggle,onDelete,onToggleSubtask}){
 const [mode,setMode]=useState('list'); const [query,setQuery]=useState(''); const [status,setStatus]=useState('all');
 const filtered=useMemo(()=>tasks.filter(t=>status==='all'||t.status===status).filter(t=>!query||`${t.title} ${t.description||''} ${t.category}`.toLowerCase().includes(query.toLowerCase())),[tasks,status,query])
 function card(task){const subs=taskSubtasks.filter(s=>s.task_id===task.id);const links=taskTagLinks.filter(l=>l.task_id===task.id);const taskTags=links.map(l=>tags.find(t=>t.id===l.tag_id)).filter(Boolean);return <article className={`advanced-task-card panel ${task.completed?'completed-task':''}`} key={task.id}><div className="advanced-task-head"><button className={`check-button ${task.completed?'checked':''}`} onClick={()=>onToggle(task)}>✓</button><div><strong>{task.title}</strong><small>{task.category} · {task.status}{task.due_date?` · ${formatShortDate(task.due_date)}`:''}{task.due_time?` · ${safeTime(task.due_time)}`:''}</small></div><span className="xp-pill">+{task.xp_reward} XP</span></div>{task.description&&<p>{task.description}</p>}{taskTags.length>0&&<div className="tag-row">{taskTags.map(tag=><span style={{borderColor:tag.color}} key={tag.id}>#{tag.name}</span>)}</div>}{subs.length>0&&<div className="subtask-list">{subs.map(s=><button className={s.completed?'done':''} onClick={()=>onToggleSubtask(s)} key={s.id}><span>{s.completed?'✓':'○'}</span>{s.title}</button>)}</div>}<div className="row-actions end"><button className="mini-action" onClick={()=>onEdit(task)}>Editar</button><button className="delete-button" onClick={()=>onDelete(task.id)}>×</button></div></article>}
 return <section className="view-stack enter-up"><header className="section-heading"><div><p className="eyebrow">GESTIÓN DE ACCIONES</p><h2>Tareas</h2><p>Organizá acciones, subtareas, etiquetas y estados. Las subtareas aumentan la XP final.</p></div><button className="primary-button" onClick={onNew}>＋ Nueva tarea</button></header><div className="toolbar-panel panel"><input placeholder="Buscar tareas…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Todos los estados</option>{STATUSES.map(([id,label])=><option value={id} key={id}>{label}</option>)}</select><button className={`mini-action ${mode==='list'?'active':''}`} onClick={()=>setMode('list')}>Lista</button><button className={`mini-action ${mode==='kanban'?'active':''}`} onClick={()=>setMode('kanban')}>Kanban</button></div>{mode==='list'?<div className="advanced-task-list">{filtered.map(card)}{!filtered.length&&<p className="muted-copy">No hay tareas para mostrar.</p>}</div>:<div className="kanban-board">{STATUSES.slice(0,5).map(([id,label])=><section className="kanban-column" key={id}><header><strong>{label}</strong><span>{filtered.filter(t=>t.status===id).length}</span></header>{filtered.filter(t=>t.status===id).map(card)}</section>)}</div>}</section>
}
