import { useEffect, useMemo, useState } from 'react'
import { calculateTaskXp } from '../lib/xp.js'
import { findCategory } from '../data/defaultCategories.js'

const EMPTY_FORM = { title:'', description:'', category_key:'default:Personal', due_date:'', due_time:'', priority:'media', status:'pendiente', subtasks:[], tag_text:'' }
function normalizeTask(task,categories,taskSubtasks=[],selectedTags=[]){const category=categories.find(i=>i.id&&i.id===task?.category_id)||categories.find(i=>i.name===task?.category)||categories[0];return{title:task?.title||'',description:task?.description||'',category_key:category?.key||'default:Personal',due_date:task?.due_date||'',due_time:task?.due_time?.slice(0,5)||'',priority:task?.priority||'media',status:task?.status||(task?.completed?'completada':'pendiente'),subtasks:taskSubtasks.map(s=>({id:s.id,title:s.title,completed:s.completed})),tag_text:selectedTags.map(t=>t.name).join(', ')}}
export default function TaskModal({open,onClose,onSave,task,categories,taskSubtasks=[],selectedTags=[]}){
 const [form,setForm]=useState(EMPTY_FORM); const [saving,setSaving]=useState(false); const autoXp=useMemo(()=>calculateTaskXp(form),[form]); const editing=Boolean(task?.id)
 useEffect(()=>{if(open)setForm(normalizeTask(task,categories,taskSubtasks,selectedTags))},[open,task,categories,taskSubtasks,selectedTags])
 if(!open)return null
 const update=(k,v)=>setForm(c=>({...c,[k]:v})); const updateSub=(index,value)=>update('subtasks',form.subtasks.map((s,i)=>i===index?{...s,title:value}:s));
 async function submit(e){e.preventDefault();setSaving(true);const category=findCategory(categories,form.category_key);const ok=await onSave({title:form.title.trim(),description:form.description.trim()||null,category:category.name,category_id:category.id||null,due_date:form.due_date||null,due_time:form.due_time||null,priority:form.priority,status:form.status,completed:form.status==='completada',completed_at:form.status==='completada'?(task?.completed_at||new Date().toISOString()):null,xp_reward:autoXp,subtasks:form.subtasks.filter(s=>s.title.trim()).map((s,position)=>({...s,title:s.title.trim(),position})),tag_names:form.tag_text.split(',').map(t=>t.trim()).filter(Boolean)},task?.id?task:null);setSaving(false);if(ok){setForm(EMPTY_FORM);onClose()}}
 return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><form className="editor-modal panel enter-up wide-modal" onSubmit={submit}><div className="modal-heading"><div><p className="eyebrow">GESTIÓN DE TAREAS</p><h2>{editing?'Editar tarea':'Nueva tarea'}</h2></div><button className="icon-button" type="button" onClick={onClose}>×</button></div>
 <label><span>Título</span><input autoFocus required maxLength="180" value={form.title} onChange={e=>update('title',e.target.value)} /></label><label><span>Descripción opcional</span><textarea rows="3" value={form.description} onChange={e=>update('description',e.target.value)} /></label>
 <div className="form-grid two-columns"><label><span>Categoría</span><select value={form.category_key} onChange={e=>update('category_key',e.target.value)}>{categories.map(c=><option value={c.key} key={c.key}>{c.icon} {c.name}</option>)}</select></label><label><span>Prioridad</span><select value={form.priority} onChange={e=>update('priority',e.target.value)}><option value="baja">Baja</option><option value="media">Media</option><option value="alta">Alta</option></select></label><label><span>Fecha máxima</span><input type="date" value={form.due_date} onChange={e=>update('due_date',e.target.value)}/></label><label><span>Hora opcional</span><input type="time" value={form.due_time} onChange={e=>update('due_time',e.target.value)}/></label><label><span>Estado</span><select value={form.status} onChange={e=>update('status',e.target.value)}><option value="pendiente">Pendiente</option><option value="en_progreso">En progreso</option><option value="pospuesta">Pospuesta</option><option value="bloqueada">Bloqueada</option><option value="cancelada">Cancelada</option><option value="completada">Completada</option></select></label><div className="xp-preview"><span>XP final calculada</span><strong>+{autoXp} XP</strong></div></div>
 <label><span>Etiquetas separadas por coma</span><input value={form.tag_text} onChange={e=>update('tag_text',e.target.value)} placeholder="urgente, cliente, presupuesto"/></label>
 <section className="subtask-editor"><div className="card-heading"><div><p className="eyebrow">SUBTAREAS</p><h3>Pasos internos</h3><p>Aumentan la recompensa final de la tarea.</p></div><button className="mini-action" type="button" onClick={()=>update('subtasks',[...form.subtasks,{title:'',completed:false}])}>＋ Agregar</button></div>{form.subtasks.map((s,i)=><div className="subtask-edit-row" key={s.id||i}><input value={s.title} onChange={e=>updateSub(i,e.target.value)} placeholder={`Subtarea ${i+1}`}/><button className="delete-button" type="button" onClick={()=>update('subtasks',form.subtasks.filter((_,x)=>x!==i))}>×</button></div>)}</section>
 <div className="modal-actions"><button className="ghost-button" type="button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={saving}>{saving?'Guardando…':editing?'Guardar cambios':'Crear tarea'}</button></div></form></div>
}
